# Generated by Django 2.1.5 on 2019-01-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
