# Generated by Django 2.1.4 on 2018-12-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181224_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Наименование',
        ),
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_time',
            field=models.TimeField(verbose_name='Время хранения'),
        ),
    ]
