# Generated by Django 2.1.4 on 2018-12-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181224_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Наименование',
            new_name='name',
        ),
    ]
