# Generated by Django 2.1.4 on 2018-12-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181224_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Величина')),
                ('description', models.CharField(default='Здесь комментарий', help_text='Место для комментарий', max_length=200, verbose_name='Комментарий')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ManyToManyField(help_text='Выберите величину', to='home.Unit'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ManyToManyField(help_text='Выберите величину', to='home.Unit'),
        ),
    ]
